# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CollegeMap' do
pod 'CYLTabBarController'
pod ‘Ono’
pod 'SDWebImage'
pod ‘KLCPopup’
end

target 'CollegeMapTests' do

end

